### PR TITLE
Slim the size of the Gem and standardize the license file / string

### PR DESCRIPTION
**Pull request by tas50**
This cuts the size of the gem we ship in 1/2

### CODE REVIEW

**Comment by gregf** [comment]
Happily merge this and get a release out today if you can fix the tests real quick?

**Comment by tas50** [comment]
@gregf Fixed up. I'd appreciate the release so we can slim down DK a few k

**Comment by gregf** [comment]
I never even gave this a thought, happy to help get the release out. Coming very soon, working on it now.

**Comment by gregf** [comment]
Should be released, let me know if there is anything else I can do for the nice people at chef.

**Pull request merged**
