### PR TITLE
Remove unsupported default image mapping

### PR DESCRIPTION
**Pull request by vsingh-msys**
### Description
 - Move method to constant for default platform image mappings.
 - Add `ubuntu-20` and refactored the hash.

### Related Resource

Fixes: https://github.com/test-kitchen/kitchen-digitalocean/issues/76

Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

### CODE REVIEW

**Comment by gregf** [comment]
Looks great, thank you.

**Comment by tas50** [comment]
@gregf Any chance you can ship this to rubygems so we can ship it in the next Chef Workstation?

**Comment by gregf** [comment]
@tas50 heading to bed, i'll do it when I wake up for sure. I really should set you up with rubygem access let's get that done.

**Comment by gregf** [comment]
@tas50 all done sorry for the delay, yesterday was nuts. Can I get you're rubygems username/email so I can add you as a owner. This way if you need to make a release and I'm not around for whatever reason you can?

**Comment by btm** [comment]
> @tas50 all done sorry for the delay, yesterday was nuts. Can I get you're rubygems username/email so I can add you as a owner. This way if you need to make a release and I'm not around for whatever reason you can?

@gregf tsmith84 -at- gmail.com

**Comment by gregf** [comment]
@btm Hello my fellow Mainer. Thank you for his info, I'll get that sorted now.

**Comment by gregf** [comment]
@tas50 you are now a owner, use it as needed.

**Comment by tas50** [comment]
Thanks @gregf. I think you're the expert here, but it'll be nice to be able to push a release if we need it.

**Pull request merged**
